// AUTO-GENERATED by scripts/build-assets.mjs from the original standalone HTML.
// Contains only the static markup (sidebar / main / modals). Do not edit by hand.
export const ISP_MARKUP = `<div class="app">
  <!-- サイドバー -->
  <div class="sidebar">
    <div class="sidebar-header">
      <h1>個別支援管理</h1>
      <p>支援計画・日誌・評価</p>
    </div>
    <div class="sidebar-menu">
      <div class="menu-section">メニュー</div>
      <button class="menu-item active" onclick="showPage('users')">👥 利用者一覧</button>
      <button class="menu-item" onclick="showPage('goals')" id="menu-goals">🎯 支援目標</button>
      <button class="menu-item" onclick="showPage('diary')" id="menu-diary">📝 支援日誌</button>
      <button class="menu-item" onclick="showPage('pickup')" id="menu-pickup">⭐ 有効支援ピックアップ</button>
      <button class="menu-item" onclick="showPage('review')" id="menu-review">📊 振り返り・評価</button>
      <button class="menu-item" onclick="showPage('nextplan')" id="menu-nextplan">📋 次期計画策定</button>
    </div>
    <div class="sidebar-footer" style="font-size:11px; color:#aaa;">
      データはブラウザに保存されます<br>
      <button class="btn" style="margin-top:8px;font-size:11px;padding:4px 8px;width:100%" onclick="exportData()">📤 エクスポート</button>
      <button class="btn" style="margin-top:4px;font-size:11px;padding:4px 8px;width:100%" onclick="document.getElementById('import-input').click()">📥 インポート</button>
      <input type="file" id="import-input" accept=".json" style="display:none" onchange="importData(this)">
    </div>
  </div>

  <!-- メインコンテンツ -->
  <div class="main">
    <div class="topbar">
      <h2 id="page-title">利用者一覧</h2>
      <div class="topbar-actions" id="topbar-actions">
        <button class="btn primary" onclick="openAddUserModal()">＋ 利用者追加</button>
      </div>
    </div>
    <div class="content" id="main-content">
      <!-- JS で描画 -->
    </div>
  </div>
</div>

<!-- 利用者追加/編集モーダル -->
<div class="modal-overlay" id="user-modal">
  <div class="modal">
    <div class="modal-header">
      <h3 id="user-modal-title">利用者追加</h3>
      <button class="btn" onclick="closeModal('user-modal')">✕</button>
    </div>
    <div class="form-row">
      <div class="form-group"><label>氏名 *</label><input type="text" id="u-name" placeholder="例: 山田 太郎"></div>
      <div class="form-group"><label>ふりがな</label><input type="text" id="u-kana" placeholder="やまだ たろう"></div>
    </div>
    <div class="form-row triple">
      <div class="form-group"><label>生年月日</label><input type="date" id="u-birth"></div>
      <div class="form-group"><label>性別</label>
        <select id="u-gender"><option value="">—</option><option>男性</option><option>女性</option><option>その他</option></select>
      </div>
      <div class="form-group"><label>障害支援区分</label>
        <select id="u-level"><option value="">—</option><option>区分1</option><option>区分2</option><option>区分3</option><option>区分4</option><option>区分5</option><option>区分6</option></select>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group"><label>サービス種別</label>
        <select id="u-service"><option value="">—</option><option>生活介護</option><option>就労継続支援A型</option><option>就労継続支援B型</option><option>就労移行支援</option><option>共同生活援助</option><option>施設入所支援</option><option>放課後等デイサービス</option><option>その他</option></select>
      </div>
      <div class="form-group"><label>相談支援事業所</label><input type="text" id="u-office" placeholder="事業所名"></div>
    </div>
    <div class="form-row single">
      <div class="form-group"><label>備考・特記事項</label><textarea id="u-memo" placeholder="医療的ケア・コミュニケーション方法など"></textarea></div>
    </div>
    <div class="modal-footer">
      <button class="btn" onclick="closeModal('user-modal')">キャンセル</button>
      <button class="btn primary" onclick="saveUser()">保存</button>
    </div>
  </div>
</div>

<!-- 支援日誌 追加/編集モーダル -->
<div class="modal-overlay" id="diary-modal">
  <div class="modal">
    <div class="modal-header">
      <h3 id="diary-modal-title">支援日誌 記録</h3>
      <button class="btn" onclick="closeModal('diary-modal')">✕</button>
    </div>
    <div class="form-row triple">
      <div class="form-group"><label>日付 *</label><input type="date" id="d-date"></div>
      <div class="form-group"><label>対応者</label><input type="text" id="d-staff" placeholder="担当職員名"></div>
      <div class="form-group"><label>参加状況</label>
        <select id="d-attend"><option>参加</option><option>欠席</option><option>早退</option><option>遅刻</option></select>
      </div>
    </div>
    <div class="form-row single">
      <div class="form-group">
        <label>関連する目標</label>
        <select id="d-goal"><option value="">— 目標を選択（任意）—</option></select>
      </div>
    </div>
    <div class="form-row single">
      <div class="form-group has-voice">
        <label>支援内容・活動</label>
        <textarea id="d-content" placeholder="本日の支援内容・活動内容を記録してください"></textarea>
        <button type="button" class="voice-btn" title="音声入力" onclick="toggleVoice('d-content',this)">🎤</button>
      </div>
    </div>
    <div class="form-row single">
      <div class="form-group has-voice">
        <label>本人の様子・反応</label>
        <textarea id="d-condition" placeholder="体調・気分・言動・反応など"></textarea>
        <button type="button" class="voice-btn" title="音声入力" onclick="toggleVoice('d-condition',this)">🎤</button>
      </div>
    </div>
    <div class="form-row single">
      <div class="form-group has-voice">
        <label>申し送り・次回への課題</label>
        <textarea id="d-note" placeholder="次の支援に向けた引き継ぎ事項"></textarea>
        <button type="button" class="voice-btn" title="音声入力" onclick="toggleVoice('d-note',this)">🎤</button>
      </div>
    </div>
    <div class="form-row single">
      <div class="form-group">
        <label>目標への取り組み評価</label>
        <div class="rating-selector" id="d-rating-sel">
          <button class="rating-btn" data-val="good" onclick="setRating('good')">✓ 良好</button>
          <button class="rating-btn" data-val="mid" onclick="setRating('mid')">△ 普通</button>
          <button class="rating-btn" data-val="bad" onclick="setRating('bad')">✗ 要支援</button>
          <button class="rating-btn" data-val="" onclick="setRating('')">— 未記入</button>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn danger" id="diary-delete-btn" onclick="deleteDiary()" style="display:none">削除</button>
      <button class="btn" onclick="closeModal('diary-modal')">キャンセル</button>
      <button class="btn primary" onclick="saveDiary()">保存</button>
    </div>
  </div>
</div>

<!-- 支援目標 追加/編集モーダル -->
<div class="modal-overlay" id="goal-modal">
  <div class="modal">
    <div class="modal-header">
      <h3 id="goal-modal-title">支援目標 設定</h3>
      <button class="btn" onclick="closeModal('goal-modal')">✕</button>
    </div>
    <div class="form-row single">
      <div class="form-group"><label>長期目標</label><textarea id="g-long" placeholder="半年〜1年間で達成を目指す目標"></textarea></div>
    </div>
    <div class="form-row single">
      <div class="form-group"><label>長期目標の手立て</label><textarea id="g-long-support" placeholder="長期目標達成に向けた支援内容・方法"></textarea></div>
    </div>
    <div class="form-row single">
      <div class="form-group"><label>短期目標 *</label><textarea id="g-short" placeholder="今期（3〜6ヶ月）で取り組む具体的な目標"></textarea></div>
    </div>
    <div class="form-row single">
      <div class="form-group"><label>短期目標の手立て</label><textarea id="g-support" placeholder="短期目標達成に向けた具体的な支援内容・方法"></textarea></div>
    </div>
    <div class="form-row">
      <div class="form-group"><label>計画開始日</label><input type="date" id="g-start"></div>
      <div class="form-group"><label>計画終了日</label><input type="date" id="g-end"></div>
    </div>
    <div class="form-row">
      <div class="form-group"><label>担当職員</label><input type="text" id="g-staff" placeholder="担当者名"></div>
      <div class="form-group"><label>達成度（0〜100%）</label><input type="number" id="g-progress" min="0" max="100" value="0" placeholder="0"></div>
    </div>
    <div class="form-row single">
      <div class="form-group"><label>備考</label><textarea id="g-memo" placeholder="その他、特記事項"></textarea></div>
    </div>
    <div class="modal-footer">
      <button class="btn danger" id="goal-delete-btn" onclick="deleteGoal()" style="display:none">削除</button>
      <button class="btn" onclick="closeModal('goal-modal')">キャンセル</button>
      <button class="btn primary" onclick="saveGoal()">保存</button>
    </div>
  </div>
</div>

<!-- 振り返り記録モーダル -->
<div class="modal-overlay" id="review-modal">
  <div class="modal">
    <div class="modal-header">
      <h3>振り返り・評価記録</h3>
      <button class="btn" onclick="closeModal('review-modal')">✕</button>
    </div>
    <div class="form-row">
      <div class="form-group"><label>評価日</label><input type="date" id="rv-date"></div>
      <div class="form-group"><label>評価期間</label><input type="text" id="rv-period" placeholder="例: 2025年4月〜6月"></div>
    </div>
    <div class="form-row single">
      <div class="form-group"><label>目標達成状況（本人評価）</label><textarea id="rv-self" placeholder="本人が感じている達成感・変化など"></textarea></div>
    </div>
    <div class="form-row single">
      <div class="form-group"><label>目標達成状況（職員評価）</label><textarea id="rv-staff" placeholder="職員から見た達成状況・成長した点"></textarea></div>
    </div>
    <div class="form-row single">
      <div class="form-group"><label>次期計画への引き継ぎ・課題</label><textarea id="rv-next" placeholder="次期の支援計画に向けた課題・継続事項"></textarea></div>
    </div>
    <div class="form-row">
      <div class="form-group">
        <label>総合評価</label>
        <select id="rv-overall">
          <option value="">—</option>
          <option value="A">A: 目標達成</option>
          <option value="B">B: おおむね達成</option>
          <option value="C">C: 一部達成</option>
          <option value="D">D: 未達成</option>
          <option value="E">E: 継続検討</option>
        </select>
      </div>
      <div class="form-group"><label>評価者</label><input type="text" id="rv-evaluator" placeholder="職員名"></div>
    </div>
    <div class="modal-footer">
      <button class="btn danger" id="review-delete-btn" onclick="deleteReview()" style="display:none">削除</button>
      <button class="btn" onclick="closeModal('review-modal')">キャンセル</button>
      <button class="btn primary" onclick="saveReview()">保存</button>
    </div>
  </div>
</div>`;
