import fs from 'node:fs';
import path from 'node:path';

const SRC = '/root/.claude/uploads/cb2c4621-a360-5212-8435-c4dad54e9493/d87a0cd3-______.html';
const html = fs.readFileSync(SRC,'utf8');

// ---- 1) markup (between <body> and <script>) ----
const bodyStart = html.indexOf('<body>') + '<body>'.length;
const scriptStart = html.indexOf('<script>', bodyStart);
let markup = html.slice(bodyStart, scriptStart).trim();

fs.mkdirSync('src/lib',{recursive:true});
const escaped = markup.replace(/\\/g,'\\\\').replace(/`/g,'\\`').replace(/\$\{/g,'\\${');
fs.writeFileSync('src/lib/ispMarkup.ts',
  '// AUTO-GENERATED by scripts/build-assets.mjs from the original standalone HTML.\n' +
  '// Contains only the static markup (sidebar / main / modals). Do not edit by hand.\n' +
  'export const ISP_MARKUP = `' + escaped + '`;\n');

// ---- 2) app JS ----
const scriptEnd = html.indexOf('</script>', scriptStart);
let code = html.slice(scriptStart + '<script>'.length, scriptEnd);

// keep from `let currentPage` (drop the localStorage-based storage layer)
const keepFrom = code.indexOf("let currentPage = 'users';");
if (keepFrom < 0) throw new Error('currentPage anchor not found');
let kept = code.slice(keepFrom);

// drop all data-seeding IIFEs + original init (everything from the first seed)
const seedFrom = kept.indexOf('(function seedHandwrittenData()');
if (seedFrom < 0) throw new Error('seed anchor not found');
// back up to the comment banner preceding it, if present
let cut = kept.lastIndexOf('// =====================', seedFrom);
if (cut < 0) cut = seedFrom;
kept = kept.slice(0, cut).trimEnd();

const storage = `// ===================== サーバー保存（全員で共有） =====================
// localStorage ではなくサーバー(SQLite)に保存する。起動時に全データを読み込み、
// 変更は差分(upsert/delete)としてサーバーへ送信する。8秒ごとに他の職員の更新も取り込む。
let _storageOK = true;
const _COLLECTION = { isp_users:'users', isp_diaries:'diaries', isp_goals:'goals', isp_reviews:'reviews' };
let _cache = { users:[], diaries:[], goals:[], reviews:[] };
let _baseline = { users:[], diaries:[], goals:[], reviews:[] };
function _clone(x){ return JSON.parse(JSON.stringify(x)); }

function _read(key){ return _clone(_cache[_COLLECTION[key]] || []); }
function _write(key, v){
  const col = _COLLECTION[key];
  _cache[col] = _clone(v);
  const base = _baseline[col] || [];
  const baseById = new Map(base.map(r => [r.id, JSON.stringify(r)]));
  const upserts = [];
  const newIds = new Set();
  (v || []).forEach(r => {
    if (!r || r.id == null) return;
    newIds.add(r.id);
    if (baseById.get(r.id) !== JSON.stringify(r)) upserts.push(r);
  });
  const deletes = base.filter(r => !newIds.has(r.id)).map(r => r.id);
  if (upserts.length === 0 && deletes.length === 0) return;
  _baseline[col] = _clone(v);
  fetch('/api/data', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ collection: col, upserts, deletes })
  }).then(res => { if (!res.ok) throw new Error('save failed ' + res.status); })
    .catch(err => {
      console.error(err);
      if (_storageOK) {
        _storageOK = false;
        alert('⚠ サーバーへの保存に失敗しました。\\n\\nネットワーク接続を確認してください。' +
          'この画面の入力は一時的に表示されていますが、保存されていない可能性があります。');
      }
    });
}

const DB = {
  get users() { return _read('isp_users'); },
  set users(v) { _write('isp_users', v); },
  get diaries() { return _read('isp_diaries'); },
  set diaries(v) { _write('isp_diaries', v); },
  get goals() { return _read('isp_goals'); },
  set goals(v) { _write('isp_goals', v); },
  get reviews() { return _read('isp_reviews'); },
  set reviews(v) { _write('isp_reviews', v); },
};

`;

const init = `

// ===================== 起動・同期 =====================
async function _loadFromServer(){
  const res = await fetch('/api/data', { cache: 'no-store' });
  if (!res.ok) throw new Error('load failed ' + res.status);
  const data = await res.json();
  return {
    users: Array.isArray(data.users) ? data.users : [],
    diaries: Array.isArray(data.diaries) ? data.diaries : [],
    goals: Array.isArray(data.goals) ? data.goals : [],
    reviews: Array.isArray(data.reviews) ? data.reviews : [],
  };
}
async function _bootstrap(){
  try {
    _cache = await _loadFromServer();
    _baseline = _clone(_cache);
  } catch (e) {
    console.error(e);
    alert('⚠ サーバーからデータを読み込めませんでした。ページを再読み込みしてください。');
  }
  renderPage('users');
  _startPolling();
}
function _startPolling(){
  setInterval(async () => {
    // 入力中(モーダル表示中)は他者の更新で画面を書き換えない
    if (document.querySelector('.modal-overlay.open')) return;
    try {
      const next = await _loadFromServer();
      if (JSON.stringify(next) === JSON.stringify(_cache)) return; // 変化なし
      _cache = next;
      _baseline = _clone(next);
      // 選択中の利用者が消えていたら選択解除
      if (selectedUserId && !_cache.users.some(u => u.id === selectedUserId)) selectedUserId = null;
      renderPage(currentPage);
    } catch (e) { /* 一時的な失敗は無視して次回に任せる */ }
  }, 8000);
}

_bootstrap();
`;

const out = storage + kept + init;
fs.mkdirSync('public',{recursive:true});
fs.writeFileSync('public/isp-app.js', out);

console.log('ispMarkup.ts bytes:', escaped.length);
console.log('isp-app.js bytes:', out.length);
console.log('markup starts:', markup.slice(0,40).replace(/\n/g,' '));
console.log('kept core starts:', kept.slice(0,40).replace(/\n/g,' '));
console.log('kept core ends:', kept.slice(-60).replace(/\n/g,' '));
